[tool.poetry]
name = "goit-hm-ds-2"
version = "0.1.0"
description = ""
authors = ["OlegDovhyi <oleg.dovgyy@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
